import { Injectable } from '@nestjs/common';
import { IWordRepository, WordFilters } from '../../domain/word.repository';
import { Word } from '../../domain/word.entity';
import { WordDifficulty } from '../../domain/word-difficulty.enum';

/** Static seed data — also used as initial pool seed */
export const MOCK_WORDS: Word[] = [
    // ── Animales · Fácil ──────────────────────────────────────────────────────
    new Word('1', 'Perro', 'Animales', WordDifficulty.EASY, ['Vecino', 'Ruido', 'Paseo', 'Puerta', 'Lealtad']),
    new Word('2', 'Gato', 'Animales', WordDifficulty.EASY, ['Altura', 'Silencio', 'Sombra', 'Independencia', 'Noche']),
    new Word('3', 'Vaca', 'Animales', WordDifficulty.EASY, ['Campo', 'Rutina', 'Blanco', 'Mañana', 'Industria']),
    new Word('4', 'Gallina', 'Animales', WordDifficulty.EASY, ['Patio', 'Alarma', 'Granja', 'Desayuno', 'Grupo']),
    new Word('5', 'Caballo', 'Animales', WordDifficulty.EASY, ['Carrera', 'Campo', 'Elegancia', 'Competencia', 'Fuerza']),
    new Word('31', 'Tiburón', 'Animales', WordDifficulty.EASY, ['Película', 'Profundidad', 'Verano', 'Miedo', 'Silencio']),
    new Word('37', 'Conejo', 'Animales', WordDifficulty.EASY, ['Rapidez', 'Primavera', 'Sorpresa', 'Campo', 'Juego']),
    new Word('40', 'Manzana', 'Comida', WordDifficulty.EASY, ['Merienda', 'Escuela', 'Rojo', 'Salud', 'Huerto']),
    new Word('43', 'Lámpara', 'Hogar', WordDifficulty.EASY, ['Noche', 'Escritorio', 'Luz', 'Lectura', 'Habitación']),
    new Word('46', 'Leche', 'Comida', WordDifficulty.EASY, ['Desayuno', 'Blanco', 'Frío', 'Vaso', 'Mañana']),
    new Word('49', 'Playa', 'Naturaleza', WordDifficulty.EASY, ['Vacaciones', 'Sol', 'Toalla', 'Descanso', 'Verano']),
    new Word('52', 'Chocolate', 'Comida', WordDifficulty.EASY, ['Antojo', 'Dulce', 'Regalo', 'Cacao', 'Infancia']),
    new Word('55', 'Tortuga', 'Animales', WordDifficulty.EASY, ['Lento', 'Playa', 'Viaje', 'Caparazón', 'Paciencia']),
    new Word('58', 'Sandía', 'Comida', WordDifficulty.EASY, ['Verano', 'Rojo', 'Semillas', 'Frío', 'Rebanada']),
    new Word('61', 'Ratón', 'Animales', WordDifficulty.EASY, ['Pequeño', 'Noche', 'Cocina', 'Rápido', 'Esquina']),
    new Word('64', 'Banana', 'Comida', WordDifficulty.EASY, ['Merienda', 'Amarillo', 'Deporte', 'Rápido', 'Cáscara']),
    new Word('67', 'Pera', 'Comida', WordDifficulty.EASY, ['Fruta', 'Dulce', 'Forma', 'Canasta', 'Merienda']),
    new Word('70', 'Lobo', 'Animales', WordDifficulty.EASY, ['Manada', 'Bosque', 'Noche', 'Aullido', 'Invierno']),
    new Word('73', 'Uva', 'Comida', WordDifficulty.EASY, ['Racimo', 'Dulce', 'Campo', 'Fiesta', 'Pequeño']),
    new Word('76', 'León', 'Animales', WordDifficulty.EASY, ['Sabana', 'Grupo', 'Fuerza', 'Descanso', 'Rey']),
    new Word('79', 'Fresa', 'Comida', WordDifficulty.EASY, ['Rojo', 'Dulce', 'Postre', 'Pequeño', 'Huerto']),
    new Word('82', 'Tigre', 'Animales', WordDifficulty.EASY, ['Selva', 'Rayas', 'Sigilo', 'Fuerza', 'Caza']),
    new Word('85', 'Durazno', 'Comida', WordDifficulty.EASY, ['Fruta', 'Verano', 'Dulce', 'Pelusa', 'Mercado']),
    new Word('88', 'Oso', 'Animales', WordDifficulty.EASY, ['Bosque', 'Invierno', 'Grande', 'Miel', 'Cueva']),
    new Word('91', 'Cocodrilo', 'Animales', WordDifficulty.EASY, ['Río', 'Silencio', 'Paciencia', 'Orilla', 'Sol']),
    new Word('94', 'Piña', 'Comida', WordDifficulty.EASY, ['Verano', 'Tropical', 'Dulce', 'Fiesta', 'Mercado']),
    new Word('97', 'Pingüino', 'Animales', WordDifficulty.EASY, ['Frío', 'Grupo', 'Blanco', 'Torpe', 'Mar']),
    new Word('100', 'Mango', 'Comida', WordDifficulty.EASY, ['Dulce', 'Verano', 'Mercado', 'Jugo', 'Color']),
    new Word('103', 'Cebra', 'Animales', WordDifficulty.EASY, ['Grupo', 'Sabana', 'Contraste', 'Movimiento', 'África']),
    new Word('106', 'Papaya', 'Comida', WordDifficulty.EASY, ['Tropical', 'Desayuno', 'Dulce', 'Semillas', 'Mercado']),
    new Word('109', 'Ardilla', 'Animales', WordDifficulty.EASY, ['Árbol', 'Rápido', 'Parque', 'Invierno', 'Pequeño']),
    new Word('112', 'Sandwich', 'Comida', WordDifficulty.EASY, ['Almuerzo', 'Rápido', 'Pan', 'Oficina', 'Merienda']),
    new Word('115', 'Loro', 'Animales', WordDifficulty.EASY, ['Color', 'Voz', 'Selva', 'Imitación', 'Jaula']),
    new Word('118', 'Melón', 'Comida', WordDifficulty.EASY, ['Verano', 'Dulce', 'Frío', 'Mercado', 'Grande']),
    new Word('121', 'Delfín', 'Animales', WordDifficulty.EASY, ['Mar', 'Grupo', 'Salto', 'Sonrisa', 'Inteligencia']),
    new Word('124', 'Mandarina', 'Comida', WordDifficulty.EASY, ['Invierno', 'Dulce', 'Gajos', 'Merienda', 'Cáscara']),
    new Word('127', 'Camello', 'Animales', WordDifficulty.EASY, ['Viaje', 'Calor', 'Resistencia', 'Arena', 'Carga']),
    new Word('130', 'Kiwi', 'Comida', WordDifficulty.EASY, ['Fruta', 'Verde', 'Pequeño', 'Desayuno', 'Cuchara']),
    new Word('133', 'Búho', 'Animales', WordDifficulty.EASY, ['Noche', 'Mirada', 'Silencio', 'Bosque', 'Sabiduría']),
    new Word('136', 'Cereza', 'Comida', WordDifficulty.EASY, ['Rojo', 'Pequeño', 'Postre', 'Dulce', 'Pastel']),
    new Word('139', 'Hormiga', 'Animales', WordDifficulty.EASY, ['Trabajo', 'Grupo', 'Pequeño', 'Suelo', 'Orden']),
    new Word('142', 'Flamenco', 'Animales', WordDifficulty.EASY, ['Rosa', 'Agua', 'Grupo', 'Laguna', 'Elegancia']),
    new Word('145', 'Colibrí', 'Animales', WordDifficulty.EASY, ['Flores', 'Pequeño', 'Rápido', 'Color', 'Aire']),
    new Word('148', 'Granada', 'Comida', WordDifficulty.EASY, ['Fruta', 'Rojo', 'Semillas', 'Dulce', 'Temporada']),
    new Word('151', 'Pulpo', 'Animales', WordDifficulty.EASY, ['Mar', 'Tinta', 'Movimiento', 'Roca', 'Inteligencia']),
    new Word('154', 'Trébol', 'Naturaleza', WordDifficulty.EASY, ['Suerte', 'Campo', 'Verde', 'Pequeño', 'Naturaleza']),
    new Word('157', 'Castor', 'Animales', WordDifficulty.EASY, ['Río', 'Madera', 'Construcción', 'Dientes', 'Bosque']),
    new Word('160', 'Naranja', 'Comida', WordDifficulty.EASY, ['Fruta', 'Jugo', 'Desayuno', 'Cítrico', 'Color']),
    new Word('163', 'Erizo', 'Animales', WordDifficulty.EASY, ['Espinas', 'Pequeño', 'Defensa', 'Jardín', 'Bola']),
    new Word('166', 'Hámster', 'Animales', WordDifficulty.EASY, ['Jaula', 'Rueda', 'Pequeño', 'Mascota', 'Noche']),
    new Word('169', 'Reno', 'Animales', WordDifficulty.EASY, ['Frío', 'Nieve', 'Viaje', 'Invierno', 'Tradición']),
    new Word('172', 'Coco', 'Comida', WordDifficulty.EASY, ['Playa', 'Tropical', 'Bebida', 'Cáscara', 'Palmera']),
    new Word('175', 'Pavo', 'Animales', WordDifficulty.EASY, ['Fiesta', 'Plumas', 'Granja', 'Cena', 'Tradición']),
    new Word('178', 'Mora', 'Comida', WordDifficulty.EASY, ['Fruta', 'Bosque', 'Oscuro', 'Dulce', 'Pequeño']),
    new Word('181', 'Canguro', 'Animales', WordDifficulty.EASY, ['Salto', 'Bolsa', 'Australia', 'Movimiento', 'Cría']),
    new Word('184', 'Limón', 'Comida', WordDifficulty.EASY, ['Ácido', 'Cocina', 'Amarillo', 'Bebida', 'Verano']),
    new Word('187', 'Panda', 'Animales', WordDifficulty.EASY, ['Bosque', 'Blanco', 'Asia', 'Bambú', 'Lento']),
    new Word('190', 'Ciruela', 'Comida', WordDifficulty.EASY, ['Fruta', 'Morado', 'Dulce', 'Temporada', 'Pequeño']),
    new Word('193', 'Mapache', 'Animales', WordDifficulty.EASY, ['Noche', 'Bosque', 'Curioso', 'Basura', 'Máscara']),
    new Word('196', 'Guayaba', 'Comida', WordDifficulty.EASY, ['Fruta', 'Aroma', 'Dulce', 'Mercado', 'Tropical']),
    new Word('199', 'Chango', 'Animales', WordDifficulty.EASY, ['Árbol', 'Selva', 'Juego', 'Grupo', 'Rápido']),
    new Word('202', 'Frambuesa', 'Comida', WordDifficulty.EASY, ['Rojo', 'Pequeño', 'Dulce', 'Bosque', 'Postre']),
    new Word('205', 'Koala', 'Animales', WordDifficulty.EASY, ['Árbol', 'Australia', 'Dormir', 'Eucalipto', 'Lento']),
    new Word('208', 'Maracuyá', 'Comida', WordDifficulty.EASY, ['Tropical', 'Ácido', 'Jugo', 'Semillas', 'Dulce']),
    // ── Varios · Medio ────────────────────────────────────────────────────────
    new Word('6', 'Pizza', 'Comida', WordDifficulty.EASY, ['Caja', 'Reunión', 'Noche', 'Entrega', 'Dividir']),
    new Word('7', 'Hamburguesa', 'Comida', WordDifficulty.EASY, ['Rápido', 'Papel', 'Cadena', 'Menú', 'Reunión']),
    new Word('8', 'Helado', 'Comida', WordDifficulty.EASY, ['Verano', 'Frío', 'Antojo', 'Color', 'Niñez']),
    new Word('9', 'Café', 'Comida', WordDifficulty.EASY, ['Mañana', 'Pausa', 'Energía', 'Charla', 'Oficina']),
    new Word('10', 'Pan', 'Comida', WordDifficulty.EASY, ['Mañana', 'Mesa', 'Bolsa', 'Horno', 'Rutina']),
    new Word('34', 'Pastel', 'Comida', WordDifficulty.EASY, ['Celebración', 'Velas', 'Reunión', 'Corte', 'Dulce']),
    new Word('11', 'Reloj', 'Hogar', WordDifficulty.MEDIUM, ['Tarde', 'Rutina', 'Ansiedad', 'Trabajo', 'Espera']),
    new Word('12', 'Televisión', 'Hogar', WordDifficulty.MEDIUM, ['Sofá', 'Canales', 'Discusión', 'Publicidad', 'Noche']),
    new Word('13', 'Celular', 'Tecnología', WordDifficulty.MEDIUM, ['Vibración', 'Pantalla', 'Mensaje', 'Dependencia', 'Bolsillo']),
    new Word('14', 'Avión', 'Transporte', WordDifficulty.MEDIUM, ['Maleta', 'Escala', 'Altura', 'Ventana', 'Viaje']),
    new Word('15', 'Bicicleta', 'Transporte', WordDifficulty.MEDIUM, ['Equilibrio', 'Infancia', 'Caída', 'Aire', 'Esfuerzo']),
    new Word('16', 'Libro', 'Hogar', WordDifficulty.MEDIUM, ['Silencio', 'Viaje', 'Historia', 'Tiempo', 'Soledad']),
    new Word('17', 'Silla', 'Hogar', WordDifficulty.MEDIUM, ['Espera', 'Oficina', 'Descanso', 'Invitado', 'Madera']),
    new Word('18', 'Llave', 'Hogar', WordDifficulty.MEDIUM, ['Puerta', 'Acceso', 'Metal', 'Bolsillo', 'Olvido']),
    new Word('19', 'Espejo', 'Hogar', WordDifficulty.MEDIUM, ['Reflejo', 'Baño', 'Imagen', 'Verdad', 'Rutina']),
    new Word('20', 'Zapato', 'Hogar', WordDifficulty.MEDIUM, ['Caminar', 'Par', 'Moda', 'Tierra', 'Salida']),
    new Word('32', 'Elefante', 'Animales', WordDifficulty.MEDIUM, ['Memoria', 'Viaje', 'Familia', 'Peso', 'Distancia']),
    new Word('35', 'Tren', 'Transporte', WordDifficulty.MEDIUM, ['Estación', 'Viaje', 'Ventana', 'Horario', 'Asiento']),
    new Word('38', 'Computadora', 'Tecnología', WordDifficulty.MEDIUM, ['Oficina', 'Pantalla', 'Trabajo', 'Tecla', 'Archivo']),
    new Word('41', 'Barco', 'Transporte', WordDifficulty.MEDIUM, ['Puerto', 'Viaje', 'Agua', 'Horizonte', 'Movimiento']),
    new Word('44', 'Camión', 'Transporte', WordDifficulty.MEDIUM, ['Carga', 'Carretera', 'Distancia', 'Entrega', 'Motor']),
    new Word('47', 'Teatro', 'Lugares', WordDifficulty.MEDIUM, ['Escenario', 'Público', 'Noche', 'Actuación', 'Aplauso']),
    new Word('50', 'Hospital', 'Lugares', WordDifficulty.MEDIUM, ['Urgencia', 'Blanco', 'Silencio', 'Turno', 'Cuidado']),
    new Word('53', 'Parque', 'Lugares', WordDifficulty.MEDIUM, ['Domingo', 'Familia', 'Pasto', 'Juego', 'Descanso']),
    new Word('56', 'Cine', 'Lugares', WordDifficulty.MEDIUM, ['Oscuro', 'Pantalla', 'Palomitas', 'Butaca', 'Estreno']),
    new Word('59', 'Biblioteca', 'Lugares', WordDifficulty.MEDIUM, ['Silencio', 'Estudio', 'Mesa', 'Lectura', 'Reglas']),
    new Word('62', 'Aeropuerto', 'Lugares', WordDifficulty.MEDIUM, ['Maletas', 'Espera', 'Salida', 'Idiomas', 'Control']),
    new Word('65', 'Submarino', 'Transporte', WordDifficulty.MEDIUM, ['Profundidad', 'Silencio', 'Exploración', 'Metal', 'Misión']),
    new Word('68', 'Estadio', 'Lugares', WordDifficulty.MEDIUM, ['Multitud', 'Evento', 'Equipo', 'Grito', 'Noche']),
    new Word('71', 'Restaurante', 'Lugares', WordDifficulty.MEDIUM, ['Mesa', 'Cuenta', 'Menú', 'Cita', 'Servicio']),
    new Word('74', 'Oficina', 'Lugares', WordDifficulty.MEDIUM, ['Escritorio', 'Horario', 'Reunión', 'Correo', 'Trabajo']),
    new Word('77', 'Supermercado', 'Lugares', WordDifficulty.MEDIUM, ['Carrito', 'Pasillo', 'Lista', 'Caja', 'Compra']),
    new Word('80', 'Museo', 'Lugares', WordDifficulty.MEDIUM, ['Silencio', 'Historia', 'Sala', 'Arte', 'Recorrido']),
    new Word('83', 'Farmacia', 'Lugares', WordDifficulty.MEDIUM, ['Receta', 'Mostrador', 'Urgencia', 'Salud', 'Turno']),
    new Word('86', 'Escuela', 'Lugares', WordDifficulty.MEDIUM, ['Aula', 'Recreo', 'Tarea', 'Horario', 'Examen']),
    new Word('89', 'Banco', 'Lugares', WordDifficulty.MEDIUM, ['Fila', 'Dinero', 'Cuenta', 'Tarjeta', 'Ciudad']),
    new Word('92', 'Motocicleta', 'Transporte', WordDifficulty.MEDIUM, ['Velocidad', 'Casco', 'Carretera', 'Ruido', 'Curva']),
    new Word('95', 'Carretera', 'Transporte', WordDifficulty.MEDIUM, ['Viaje', 'Línea', 'Distancia', 'Curva', 'Destino']),
    new Word('98', 'Correo', 'Lugares', WordDifficulty.MEDIUM, ['Mensaje', 'Entrega', 'Espera', 'Buzón', 'Dirección']),
    new Word('101', 'Ascensor', 'Hogar', WordDifficulty.MEDIUM, ['Botón', 'Edificio', 'Espera', 'Piso', 'Movimiento']),
    new Word('104', 'Maleta', 'Hogar', WordDifficulty.MEDIUM, ['Viaje', 'Ropa', 'Aeropuerto', 'Cierre', 'Destino']),
    new Word('107', 'Puerta', 'Hogar', WordDifficulty.MEDIUM, ['Entrada', 'Llave', 'Salida', 'Casa', 'Golpe']),
    new Word('110', 'Calendario', 'Hogar', WordDifficulty.MEDIUM, ['Fecha', 'Mes', 'Plan', 'Evento', 'Pared']),
    new Word('113', 'Puerto', 'Lugares', WordDifficulty.MEDIUM, ['Barco', 'Carga', 'Agua', 'Viaje', 'Ciudad']),
    new Word('116', 'Contrato', 'Hogar', WordDifficulty.MEDIUM, ['Firma', 'Acuerdo', 'Trabajo', 'Papel', 'Compromiso']),
    new Word('119', 'Garaje', 'Hogar', WordDifficulty.MEDIUM, ['Auto', 'Casa', 'Puerta', 'Espacio', 'Herramienta']),
    new Word('122', 'Micrófono', 'Tecnología', WordDifficulty.MEDIUM, ['Escenario', 'Voz', 'Evento', 'Cable', 'Público']),
    new Word('125', 'Globo', 'Hogar', WordDifficulty.MEDIUM, ['Fiesta', 'Aire', 'Color', 'Niñez', 'Techo']),
    new Word('128', 'Teclado', 'Tecnología', WordDifficulty.MEDIUM, ['Escribir', 'Oficina', 'Mensaje', 'Teclas', 'Trabajo']),
    new Word('131', 'Pasaporte', 'Hogar', WordDifficulty.MEDIUM, ['Viaje', 'Documento', 'Control', 'Frontera', 'Identidad']),
    new Word('134', 'Factura', 'Hogar', WordDifficulty.MEDIUM, ['Pago', 'Cuenta', 'Compra', 'Fecha', 'Documento']),
    new Word('137', 'Semilla', 'Naturaleza', WordDifficulty.MEDIUM, ['Tierra', 'Inicio', 'Crecimiento', 'Planta', 'Pequeño']),
    new Word('140', 'Mochila', 'Hogar', WordDifficulty.MEDIUM, ['Espalda', 'Viaje', 'Escuela', 'Carga', 'Cierre']),
    new Word('143', 'Alarma', 'Hogar', WordDifficulty.MEDIUM, ['Mañana', 'Sonido', 'Urgencia', 'Despertar', 'Botón']),
    new Word('146', 'Candado', 'Hogar', WordDifficulty.MEDIUM, ['Metal', 'Seguridad', 'Llave', 'Puerta', 'Cierre']),
    new Word('149', 'Andén', 'Transporte', WordDifficulty.MEDIUM, ['Tren', 'Espera', 'Maleta', 'Salida', 'Estación']),
    new Word('152', 'Termómetro', 'Hogar', WordDifficulty.MEDIUM, ['Temperatura', 'Salud', 'Medición', 'Vidrio', 'Clima']),
    new Word('155', 'Linterna', 'Hogar', WordDifficulty.MEDIUM, ['Oscuridad', 'Exploración', 'Pilas', 'Noche', 'Luz']),
    new Word('158', 'Antena', 'Tecnología', WordDifficulty.MEDIUM, ['Señal', 'Techo', 'Comunicación', 'Altura', 'Transmisión']),
    new Word('161', 'Cartera', 'Hogar', WordDifficulty.MEDIUM, ['Dinero', 'Bolsillo', 'Tarjeta', 'Documento', 'Pérdida']),
    new Word('164', 'Túnel', 'Lugares', WordDifficulty.MEDIUM, ['Oscuridad', 'Paso', 'Carretera', 'Montaña', 'Salida']),
    new Word('167', 'Archivo', 'Hogar', WordDifficulty.MEDIUM, ['Documento', 'Oficina', 'Orden', 'Carpeta', 'Información']),
    new Word('170', 'Peaje', 'Transporte', WordDifficulty.MEDIUM, ['Carretera', 'Pago', 'Cabina', 'Viaje', 'Paso']),
    new Word('173', 'Grúa', 'Transporte', WordDifficulty.MEDIUM, ['Construcción', 'Altura', 'Carga', 'Ciudad', 'Movimiento']),
    new Word('176', 'Radar', 'Tecnología', WordDifficulty.MEDIUM, ['Señal', 'Detección', 'Movimiento', 'Pantalla', 'Control']),
    new Word('179', 'Pasillo', 'Hogar', WordDifficulty.MEDIUM, ['Casa', 'Paso', 'Habitación', 'Largo', 'Interior']),
    new Word('182', 'Impresora', 'Tecnología', WordDifficulty.MEDIUM, ['Papel', 'Tinta', 'Oficina', 'Documento', 'Botón']),
    new Word('185', 'Balón', 'Deportes', WordDifficulty.MEDIUM, ['Juego', 'Equipo', 'Cancha', 'Movimiento', 'Golpe']),
    new Word('188', 'Submarino', 'Transporte', WordDifficulty.MEDIUM, ['Puerto', 'Viaje', 'Agua', 'Horizonte', 'Movimiento']),
    new Word('194', 'Elevador', 'Hogar', WordDifficulty.MEDIUM, ['Piso', 'Botón', 'Edificio', 'Subir', 'Espera']),
    new Word('197', 'Tienda', 'Lugares', WordDifficulty.MEDIUM, ['Compra', 'Mostrador', 'Cliente', 'Producto', 'Dinero']),
    new Word('200', 'Recibo', 'Hogar', WordDifficulty.MEDIUM, ['Pago', 'Compra', 'Papel', 'Fecha', 'Caja']),
    new Word('203', 'Tráfico', 'Lugares', WordDifficulty.MEDIUM, ['Ciudad', 'Espera', 'Carretera', 'Ruido', 'Hora']),
    new Word('206', 'Bodega', 'Hogar', WordDifficulty.MEDIUM, ['Almacenamiento', 'Caja', 'Espacio', 'Oscuro', 'Casa']),
    new Word('209', 'Tarjeta', 'Hogar', WordDifficulty.MEDIUM, ['Pago', 'Plástico', 'Cuenta', 'Bolsillo', 'Banco']),
    // ── Varios · Difícil ──────────────────────────────────────────────────────
    new Word('21', 'Nube', 'Naturaleza', WordDifficulty.HARD, ['Cambio', 'Altura', 'Forma', 'Sombra', 'Paso']),
    new Word('22', 'Sombrero', 'Hogar', WordDifficulty.HARD, ['Sol', 'Estilo', 'Campo', 'Protección', 'Evento']),
    new Word('23', 'Ventana', 'Hogar', WordDifficulty.HARD, ['Luz', 'Marco', 'Aire', 'Vista', 'Dentro']),
    new Word('24', 'Puente', 'Lugares', WordDifficulty.HARD, ['Río', 'Conexión', 'Paso', 'Altura', 'Ciudad']),
    new Word('25', 'Semáforo', 'Lugares', WordDifficulty.HARD, ['Espera', 'Cruce', 'Orden', 'Ciudad', 'Color']),
    new Word('26', 'Arena', 'Naturaleza', WordDifficulty.HARD, ['Verano', 'Playa', 'Tiempo', 'Grano', 'Huella']),
    new Word('27', 'Hielo', 'Naturaleza', WordDifficulty.HARD, ['Frío', 'Transparente', 'Verano', 'Bebida', 'Cambio']),
    new Word('28', 'Sombra', 'Naturaleza', WordDifficulty.HARD, ['Sol', 'Figura', 'Suelo', 'Silencio', 'Forma']),
    new Word('29', 'Río', 'Naturaleza', WordDifficulty.HARD, ['Movimiento', 'Puente', 'Agua', 'Viaje', 'Orilla']),
    new Word('30', 'Fuego', 'Naturaleza', WordDifficulty.HARD, ['Calor', 'Noche', 'Luz', 'Riesgo', 'Reunión']),
    new Word('33', 'Escalera', 'Hogar', WordDifficulty.HARD, ['Altura', 'Paso', 'Edificio', 'Subir', 'Cambio']),
    new Word('36', 'Bosque', 'Naturaleza', WordDifficulty.HARD, ['Silencio', 'Camino', 'Sombra', 'Naturaleza', 'Eco']),
    new Word('39', 'Desierto', 'Naturaleza', WordDifficulty.HARD, ['Calor', 'Extensión', 'Silencio', 'Viaje', 'Soledad']),
    new Word('42', 'Eco', 'Naturaleza', WordDifficulty.HARD, ['Montaña', 'Sonido', 'Repetición', 'Distancia', 'Voz']),
    new Word('45', 'Isla', 'Naturaleza', WordDifficulty.HARD, ['Agua', 'Aislamiento', 'Viaje', 'Palmera', 'Lejanía']),
    new Word('48', 'Viento', 'Naturaleza', WordDifficulty.HARD, ['Movimiento', 'Invisible', 'Frío', 'Cambio', 'Sonido']),
    new Word('51', 'Silencio', 'Abstracto', WordDifficulty.HARD, ['Noche', 'Biblioteca', 'Espera', 'Tensión', 'Calma']),
    new Word('54', 'Huella', 'Abstracto', WordDifficulty.HARD, ['Paso', 'Arena', 'Rastro', 'Presencia', 'Suelo']),
    new Word('57', 'Relámpago', 'Naturaleza', WordDifficulty.HARD, ['Tormenta', 'Luz', 'Noche', 'Rápido', 'Cielo']),
    new Word('60', 'Niebla', 'Naturaleza', WordDifficulty.HARD, ['Mañana', 'Visibilidad', 'Frío', 'Carretera', 'Misterio']),
    new Word('63', 'Espejismo', 'Abstracto', WordDifficulty.HARD, ['Calor', 'Distancia', 'Ilusión', 'Camino', 'Desierto']),
    new Word('66', 'Horizonte', 'Naturaleza', WordDifficulty.HARD, ['Distancia', 'Mar', 'Cielo', 'Límite', 'Atardecer']),
    new Word('69', 'Reflejo', 'Abstracto', WordDifficulty.HARD, ['Agua', 'Imagen', 'Luz', 'Superficie', 'Distorsión']),
    new Word('72', 'Ceniza', 'Naturaleza', WordDifficulty.HARD, ['Fuego', 'Gris', 'Restos', 'Viento', 'Ligero']),
    new Word('75', 'Ola', 'Naturaleza', WordDifficulty.HARD, ['Mar', 'Movimiento', 'Espuma', 'Ritmo', 'Playa']),
    new Word('78', 'Susurro', 'Abstracto', WordDifficulty.HARD, ['Cerca', 'Secreto', 'Bajo', 'Noche', 'Confianza']),
    new Word('81', 'Raíz', 'Naturaleza', WordDifficulty.HARD, ['Tierra', 'Origen', 'Profundo', 'Árbol', 'Base']),
    new Word('84', 'Eclipse', 'Naturaleza', WordDifficulty.HARD, ['Cielo', 'Sombra', 'Evento', 'Luz', 'Tiempo']),
    new Word('87', 'Brisa', 'Naturaleza', WordDifficulty.HARD, ['Suave', 'Verano', 'Movimiento', 'Playa', 'Fresco']),
    new Word('90', 'Cristal', 'Hogar', WordDifficulty.HARD, ['Transparente', 'Frágil', 'Ventana', 'Luz', 'Reflejo']),
    new Word('93', 'Labios', 'Abstracto', WordDifficulty.HARD, ['Palabra', 'Sonrisa', 'Secreto', 'Cerca', 'Color']),
    new Word('96', 'Sombrilla', 'Hogar', WordDifficulty.HARD, ['Playa', 'Protección', 'Arena', 'Sol', 'Descanso']),
    new Word('99', 'Latido', 'Abstracto', WordDifficulty.HARD, ['Pecho', 'Ritmo', 'Vida', 'Silencio', 'Urgencia']),
    new Word('102', 'Refugio', 'Abstracto', WordDifficulty.HARD, ['Tormenta', 'Protección', 'Miedo', 'Noche', 'Seguridad']),
    new Word('105', 'Destino', 'Abstracto', WordDifficulty.HARD, ['Viaje', 'Decisión', 'Futuro', 'Camino', 'Elección']),
    new Word('108', 'Suspiro', 'Abstracto', WordDifficulty.HARD, ['Cansancio', 'Alivio', 'Silencio', 'Emoción', 'Pecho']),
    new Word('111', 'Instante', 'Abstracto', WordDifficulty.HARD, ['Breve', 'Recuerdo', 'Tiempo', 'Cambio', 'Momento']),
    new Word('114', 'Esquina', 'Lugares', WordDifficulty.HARD, ['Calle', 'Encuentro', 'Giro', 'Ciudad', 'Punto']),
    new Word('123', 'Umbral', 'Abstracto', WordDifficulty.HARD, ['Entrada', 'Límite', 'Paso', 'Inicio', 'Cambio']),
    new Word('126', 'Penumbra', 'Abstracto', WordDifficulty.HARD, ['Luz', 'Sombra', 'Tarde', 'Misterio', 'Interior']),
    new Word('129', 'Raudal', 'Naturaleza', WordDifficulty.HARD, ['Agua', 'Fuerza', 'Río', 'Ruido', 'Movimiento']),
    new Word('132', 'Quimera', 'Abstracto', WordDifficulty.HARD, ['Sueño', 'Imposible', 'Imaginación', 'Deseo', 'Ilusión']),
    new Word('135', 'Aurora', 'Naturaleza', WordDifficulty.HARD, ['Cielo', 'Color', 'Frío', 'Norte', 'Luz']),
    new Word('138', 'Vacío', 'Abstracto', WordDifficulty.HARD, ['Espacio', 'Silencio', 'Ausencia', 'Interior', 'Nada']),
    new Word('141', 'Latitud', 'Abstracto', WordDifficulty.HARD, ['Mapa', 'Coordenada', 'Distancia', 'Tierra', 'Ubicación']),
    new Word('147', 'Espiral', 'Abstracto', WordDifficulty.HARD, ['Forma', 'Centro', 'Movimiento', 'Crecimiento', 'Infinito']),
    new Word('150', 'Umbría', 'Naturaleza', WordDifficulty.HARD, ['Sombra', 'Bosque', 'Fresco', 'Luz', 'Refugio']),
    new Word('156', 'Ecosistema', 'Naturaleza', WordDifficulty.HARD, ['Naturaleza', 'Equilibrio', 'Vida', 'Relación', 'Entorno']),
    new Word('159', 'Paradoja', 'Abstracto', WordDifficulty.HARD, ['Contradicción', 'Idea', 'Lógica', 'Pensamiento', 'Duda']),
    new Word('162', 'Nebulosa', 'Abstracto', WordDifficulty.HARD, ['Espacio', 'Color', 'Estrella', 'Polvo', 'Universo']),
    new Word('165', 'Ocaso', 'Naturaleza', WordDifficulty.HARD, ['Tarde', 'Color', 'Cielo', 'Final', 'Luz']),
    new Word('168', 'Resiliencia', 'Abstracto', WordDifficulty.HARD, ['Fuerza', 'Caída', 'Aprendizaje', 'Superación', 'Tiempo']),
    new Word('171', 'Éter', 'Abstracto', WordDifficulty.HARD, ['Espacio', 'Invisible', 'Teoría', 'Aire', 'Antiguo']),
    new Word('174', 'Utopía', 'Abstracto', WordDifficulty.HARD, ['Ideal', 'Sociedad', 'Sueño', 'Perfecto', 'Imposible']),
    new Word('177', 'Entropía', 'Abstracto', WordDifficulty.HARD, ['Desorden', 'Sistema', 'Cambio', 'Tiempo', 'Energía']),
    new Word('180', 'Crisálida', 'Naturaleza', WordDifficulty.HARD, ['Cambio', 'Proceso', 'Naturaleza', 'Espera', 'Transformación']),
    new Word('183', 'Preludio', 'Abstracto', WordDifficulty.HARD, ['Inicio', 'Música', 'Antes', 'Anticipación', 'Escena']),
    new Word('186', 'Ancla', 'Transporte', WordDifficulty.HARD, ['Mar', 'Peso', 'Detener', 'Barco', 'Fondo']),
    new Word('189', 'Resplandor', 'Abstracto', WordDifficulty.HARD, ['Luz', 'Brillo', 'Intenso', 'Oscuridad', 'Energía']),
    new Word('192', 'Frontera', 'Abstracto', WordDifficulty.HARD, ['Límite', 'País', 'Paso', 'Control', 'Mapa']),
    new Word('195', 'Epílogo', 'Abstracto', WordDifficulty.HARD, ['Final', 'Historia', 'Después', 'Cierre', 'Narración']),
    new Word('198', 'Oasis', 'Naturaleza', WordDifficulty.HARD, ['Desierto', 'Agua', 'Descanso', 'Palmera', 'Refugio']),
    new Word('201', 'Crepúsculo', 'Naturaleza', WordDifficulty.HARD, ['Tarde', 'Luz', 'Transición', 'Cielo', 'Silencio']),
    new Word('204', 'Quórum', 'Abstracto', WordDifficulty.HARD, ['Grupo', 'Decisión', 'Reunión', 'Regla', 'Número']),
    new Word('207', 'Catarsis', 'Abstracto', WordDifficulty.HARD, ['Emoción', 'Liberación', 'Lágrima', 'Proceso', 'Alivio']),
];

@Injectable()
export class MockWordRepository implements IWordRepository {
    async getRandomWord(filters?: WordFilters): Promise<Word | null> {
        let pool = MOCK_WORDS;

        if (filters?.category) {
            pool = pool.filter(
                (w) => w.category.toLowerCase() === filters.category!.toLowerCase(),
            );
        }

        if (filters?.difficulty) {
            pool = pool.filter((w) => w.difficulty === filters.difficulty);
        }

        if (pool.length === 0) return null;

        return pool[Math.floor(Math.random() * pool.length)];
    }

    async getAllCategories(): Promise<string[]> {
        return [...new Set(MOCK_WORDS.map((w) => w.category))];
    }
}
